import { Sidebar } from '@/components'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface IRoot {
    children: React.ReactNode | React.ReactNode[]
}

export default function RootLayout({ children }: IRoot) {
  return (
        <html className='h-screen w-screen'>
            <body className='h-screen w-screen bg-[#EFF1F3] flex'>
                <Sidebar />
                {children}
            </body>
        </html>
  )
}
